### PR TITLE
Views

### PR DESCRIPTION
**Pull request by csullins**
Latest 'views' branch pull request

### CODE REVIEW

**Review by MogleyBear06 — DISMISSED** [review]
Looks great. Thanks.

**Review by avanijadeja — APPROVED** [review]
good job.

**Review by avanijadeja — APPROVED** [review]
good job

**Review by avanijadeja — APPROVED** [review]
good job

**Review by Jflatley487 — APPROVED** [review]

**Review by jackckendrick — APPROVED** [review]

**Pull request merged**
